### ISSUE TITLE
Exposing Gyro to RPCS3

### ISSUE THREAD

**Issue by rawdatafeel** [hhd-dev/hhd#39]
This may be out of scope for HHD, apologies and please close if so.

I am on a ROG Ally, using Bazzite with the dualsense edge configuration applied. I am trying to configure gyro in RPCS3. The instructions are pretty much to just add your user to the input group and to disable Steam input.

However, it looks like gyro is still not exposed in RPCS3 even after doing that. Gyro works fine with my external controller though.

To configure, you open RPCS3, open the pads menu, select SDL, select your controller in the drop-down menu. Click configure under `Motion Controls`, and move your controller around to make sure it's working.

I am interested in this for Folklore support primarily but a simple game to test this would be [Super Rub'a'Dub](https://wiki.rpcs3.net/index.php?title=Super_Rub%27a%27Dub).

**Comment by antheas** [comment]
It is not out of scope.

We want to improve documentation.

Gyro should be working in all controller modes including xbox

The dualsense edge is a rare controller. There's a chance it is not detected by the emulator due to a missing rule.

When you get it working, can you document what you did to do it?

If it is just edge mode in the RPCS3 emulator, can you open an issue in their repo and tag me?

**Comment by NightHammer1000** [comment]
Implementing a DSU Server like Handheld Companion has would be great.
Sometimes SDL just dont want to use the Gyro.

**Comment by antheas** [comment]
Yeah I have discussed this and it's one of the planned features. Prioritization etc

You also can't use steam input and gyro at the same time right now, which is not ideal

**Comment by antheas** [comment]
The gyro calibration is perfect on the ally. The accelerometer calibration is not :)

If you want to help, use `hhd.contrib evdev` to compare the motions device from hhd to a real dualsense controller.

With both controllers still you should be getting similar values, but you dont. Because the math is wrong on my end.

I only have a legion go which does not have a proper imu for me to test.

If you do figure it out, the sensitivity of the accelerometer can be found here:
https://github.com/hhd-dev/hhd/blob/99f021042dcc9939d476003dee4d0117a92520ca/src/hhd/controller/virtual/dualsense/const.py#L127

That will fix it for all supported devices.

Also, having a mathematical reason for it will be great too. The gyro value for example is derived from the hid_playstation driver so you will notice it is exactly the same. I did the same for the accelerometer but failed.

**Comment by antheas** [comment]
Unfortunately, the numbers look to have a similar magnitude to me.

I noticed the ally had different axis on the accelerometer and gyro

So I made them the same. If you are not in Bazzite, try update unstable and see if it is better.

**Comment by antheas** [comment]
https://github.com/hhd-dev/hhd/releases/tag/v1.3.12 adds allowing flipping the roll axis, which should fix some issues with RPCS3

**Comment by antheas** [comment]
Fixed for the upcoming version. RPCS 3 uses accelerometer values, not gyro. Upcoming version fixes their scaling and their axis.
