### ISSUE TITLE
[ROG Ally] Cater for triggers that don't register the max value when fully pressed

### ISSUE THREAD

**Issue by gmartsenkov** [hhd-dev/hhd#45]
It's a common issue that the shoulder trigger buttons don't work correctly. That is usually fixed through Armory Crate by setting a max percentage on each triggers. 

How easy would it be to make this on option here? Also I don't mind forking and patching and building from source - it get's pretty annoying with racing games for example.

For reference my right trigger when fully pressed goes to around 28000 instead of 32767. 
Example - https://www.youtube.com/watch?v=SIXmsfNa0PY

**Comment by antheas** [comment]
You mean adding threshold and scale settings for the triggers and joysticks? 

It is a planned feature but it will not come soon. It will come with controller remapping as there needs to be a structural change for it to be supported.

It is hard to make it a choice right now because it will clutter the UI. I will leave the issue open until I get to it.

But as a sidenote, your unit is defective, this is not supposed to happen. That menu is not for calibration, it is for setting threshold limits to get earlier activation (e.g., mouseclick triggers). In my personal opinion you should RMA it.

If you want a quick patch, you can add an if statement here, and scale `ev['value']` to taste.
https://github.com/hhd-dev/hhd/blob/c4a0407c09ccdf53d03c32b19349a5b66dfe8484/src/hhd/controller/base.py#L384

**Comment by antheas** [comment]
Also, you can try calibrating (not setting limits) your controller with Armory Crate and see if the calibration carries over to linux.

Asus made the baffling decision to make the controller always reset its mappings, so its very likely they will not. But it is worth a try.

**Comment by gmartsenkov** [comment]
That's exactly what i meant, thanks for the tip on how to patch! I ended up returning it and getting a new one from a different retailer that doesn't seem to have this problem 😄

**Comment by antheas** [comment]
Not the best right now but I added support for it through an env variable (https://github.com/hhd-dev/hhd/commit/018dbd35ed0a18cd0781ff4570d1991352f279d0).

You can customize below to taste for any handheld controller. Its not the manufacturer controls and not in the gui, but it should suffice for now.
```bash
export HHD_CALIB=$(cat <<-END
{
    "ls_x": {"min": -1, "max": 1, "deadzone": 0.05},
    "ls_y": {"min": -1, "max": 1, "deadzone": 0.05},
    "rs_x": {"min": -1, "max": 1, "deadzone": 0.05},
    "rs_y": {"min": -1, "max": 1, "deadzone": 0.05},
    "lt": {"min": 0, "max": 1, "deadzone": 0.05},
    "rt": {"min": 0, "max": 1, "deadzone": 0.05}
}
END
)
```
