### ISSUE TITLE
[Feature Request] Auto-disable gyro when it is not used

### ISSUE THREAD

**Issue by bakamomi** [hhd-dev/hhd#63]
On GPD Win Max 2 (2003) setting Motion HZ to 1600 uses whopping 12% of one cpu core. Setting HZ to 50 reduces load to 2%, but it's still a lot.

Example output from systemd:
```
     Loaded: loaded (/etc/systemd/system/hhd_local@.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-05-02 23:01:23 UTC; 31s ago
   Main PID: 12976 (hhd)
      Tasks: 4 (limit: 57414)
     Memory: 38.0M
        CPU: 4.297s
```
In 30 seconds since the daemon launch, it already used 4 seconds of CPU time.

I don't know how it's implemented in HHD, but can you do something about this? Just a couple of ideas out of the top of my head:
1. Rewrite polling in a lower-level language like C/Rust?
2. Pause polling when gamepad isn't used. For example, poll just once in 2-3 seconds if standard xbox buttons haven't been used in a minute?

**Comment by antheas** [comment]
There is no measurable performance difference between 400hz and 1600hz, so 12% is not that big of an issue, the actuality is around 4-6% at 400hz, and if someone thinks that's too expensive, they can lower to 100hz which is also acceptable. When disabling gyro, utilization drops even further to .5% (controller still needs to output events, otherwise steam breaks).

Starting hhd takes around 2s of CPU time which could be better, but at the same time it is doing a lot of stuff, so you have to wait for utilization to stabilize first.

As for your points:
1) Most of the utilization, at least for devices that use the IIO subsystem such as yours, is due to the kernel. You can run the command time and see that system time accounts for around half of the CPU utilization. At most youre looking at halving the CPU usage, if you have a theoretical programming language that does not use CPU cycles.  Handheld Daemon has been optimized aggressively and is faster than alternative compiled solutions.

At the end of the day, 1600hz is 1600 times you have to wake up the thread, sample the iio buffer, and write the events out, and those syscalls are where most of the cost is, not python.

2) I'm thinking of a good heuristic for disabling gyro, but it is on the backburner for now. I did add one for the touchpad.

As for how sampling is done, it is not done by Handheld Daemon. At startup, Handheld Daemon marshals the iio subsystem with either the appropriate interrupts (if your device has them) or the hrtimer kernel module. Then the kernel fills the buffer and wakes up hhd when there is a new sample, so it is not something that can be downregulated without disabling the buffer and restarting once gyro is needed.

At the end of the day, 4% of one core of a 8 core/16t machine is .3% CPU utilization, which translates to a transient rise in average PPT from 3.25-4.15W (at least on my device) to 4.25W when the device is completely idle, and which is completely washed out when a browser, a game, or steam are active.

Hopefully this answers your questions

**Comment by antheas** [comment]
You can always use the desktop version of the overlay to disable gyro or controller emulation when it is not needed. When you do that, the utilization will drop to 0. Or mouse mode, which also disables the controller emulation, I just have not found a way to do it automatically.

**Comment by antheas** [comment]
Added xbox elite controller emulation and rgb controls. Therefore, the only reason to use dualsense is for gyro and touchpad for steam input. 

Gyro is autodisabled when using xbox style controllers.

In addition, double tapping the qam button will now open hhd in desktop mode (https://github.com/hhd-dev/hhd/commit/137e547c872d991499df6533759d9f38b73d88a6), so settings can be changed quickly.
