### ISSUE TITLE
GPD Win 4 Gyro not working

### ISSUE THREAD

**Issue by DocMAX** [hhd-dev/hhd#67]
Isn't it supposed to work? In Steam the Gryo test doesn't do anything. PS5 Controller is detected, though.
It's a GPD Win 4 6800U.

![grafik](https://github.com/hhd-dev/hhd/assets/5351323/31a80786-461c-48ba-882a-c47a43f3243d)

**Comment by antheas** [comment]
Post your dmesg logs from this boot

**Comment by antheas** [comment]
Also make sure you have the dkms package for gyro for your device for arch https://aur.archlinux.org/packages/bmi260-dkms

**Comment by DocMAX** [comment]
Ah, bmi260 did it! I used https://aur.archlinux.org/packages/bmi160-aya-neo-dkms-git before.
Thanks!

**Comment by antheas** [comment]
For anyone referencing this in the future, the bmi160 fix applies to 1-2 obscure 2022 devices that have a weird ACPI entry and the fix is part of the Linux kernel as of 6.9.

That dkms package may not work though.

Over 90% of devices use a bmi260, and the kernel module is not submitted to the kernel yet.

Then there are two devices that use the bmi323, the Ally and an ayaneo device. Support for those is added as of 6.8 or 6.9 I want to say.
